### ISSUE TITLE
Audio support 

### ISSUE THREAD

**Issue by maded2** [mackieks/Shinobi-Scaler#1]
Fantastic project.   Any plans to add audio support? There's a forum thread on adding a cheap ADC so the audio is mixed into the hdmi signal for modern TV.

**Comment by mackieks** [comment]
Hi! Glad you like it. Since the TV5725 doesn't have HDMI out, I assume you mean [integrating a VGA2HDMI converter?](https://www.vandoeselaar.com/tinkering/modding-a-gbs-8200/#:~:text=*update%20to%20show%20the%20connections%20to%20the%20VGA2HDMI%20converter)

While it's totally doable, it's not a priority of mine. Shinobi is mostly intended for portablizing where HDMI (and audio over HDMI) are less useful than VGA. Maybe someone else will take up the mantle and do a board spin.
