### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZeFoxii** [mackieks/Shinobi-Scaler#6]
Hi I tried to build one of these and I'm at the end of my tether with this. I have burned myself and I was stubborn not asking this earlier. do you have some form of contact? I don't have the skill level to build one of these but I want one. I am also willing to send the parts I haven't fucked up/ what's left of the ones I did.

**Comment by ZeFoxii** [comment]
If you are willing to g to sell me one how much would it cost.

**Comment by biggestsonicfan** [comment]
Where did you source your ESP-06s?

**Comment by ZeFoxii** [comment]
From his link on AliExpress

**Comment by biggestsonicfan** [comment]
You must have done it a long time ago because that link is gone and the store no longer carries them lol.

I am currently working on a fork of Shinobi to replace the ESP-06 and migrate the design to KiCad, although I haven't had much time to work on it lately.

There are other ways to have Shinobi made, alebit it at a very large expense. JLCPCB allows you to [consign parts](https://jlcpcb.com/help/article/245-How-to-consign-parts-to-JLCPCB), so you can ship them the parts to have them fabricated, though I do think the minimum order is 5 still, so adding up all the components on top of the PCB fabrication would be a fairly pricey endeavor.

I will most likely be doing a 5 board run once my KiCad version is finished.

**Comment by ZeFoxii** [comment]
Well if you do make one I wouldn't mind buying it, but I also don't want what I don't have the skill to use to just sit around, if you have the skill to make it could I ship it to you pay labor etc.. and have you ship it back? 

Because I burnt my hand pretty bad on multiple occasions trying to make this. And I really want one but I dont have the skill to do it.

**Comment by biggestsonicfan** [comment]
Sadly I don't know if I have the skill or not as I don't have the PCBs. I have components except for the ESP-06s, but I plan on spinning different revision of the Shinobi and getting a stencil made to aid in the solder paste process. Keep an eye on this repo to see when the KiCad version goes live and I should spin boards shortly after that.

EDIT: If you want me to take a crack at it you can get in contact with me outside the issue and we can arrange things. It would be good practice before I spin my other boards.

**Comment by ZeFoxii** [comment]
I feel like I could do it if the components weren't 0402, I felt confident with "everything else" 0603 tps module etc. maybe in the future I could make the pcb 1-2mm larger and pay someone on Fiverr to use 0603 instead of 0402

**Comment by mackieks** [comment]
The sudden & unexpected disappearance of all ESP-06s has been a real bummer. I brought the ESP8266 and its support components into the design this past weekend and it looks promising. I'll try to upload a new supply-chain secure rev within a month or so.

Re: your assembly troubles, the board was never designed to be hand-soldered.

You should get a steel solderpaste stencil from JLCPCB or OSHStencils, place the components with tweezers or a vacuum pencil, and reflow with hot air, a hot plate, or a reflow oven. Magnification helps during placement but is by no means required.

**Comment by biggestsonicfan** [comment]
> I brought the ESP8266 and its support components into the design this past weekend and it looks promising. I'll try to upload a new supply-chain secure rev within a month or so.

Ah so should I wait on the KiCad PR?

**Comment by mackieks** [comment]
> Ah so should I wait on the KiCad PR?

Don't let me stop you! I probably won't finish up the new version until January. Also I'm implementing the ESP-06 1:1 with an ESP8266, not the ESP8285 that you were interested in.

**Comment by ZeFoxii** [comment]
Hey just following up since you said January. Have you updated the board? Side note when you say ESP8266 do you mean the esp module or the one with drop mount pins?

**Comment by biggestsonicfan** [comment]
It's just a replacement for the ESP-06 module. Instead of soldering the module on the board it will be the components that were inside the ESP-06 module directly on the board, adding more SMT components. The design change won't make the assembly of the board any easier, in fact it might make it slightly harder.

I did manage to locate some ESP-06 modules after months of looking and once they arrive I will verify that they are the correct version and then place an order for a batch the current revision of Shinobi Scaler PCBs. If they are not the correct version, I will wait until the 2024 design revision drops.

**Comment by ZeFoxii** [comment]
Why not just use an esp12? Wouldn't it be basically the same thing just easy to solder?

**Comment by biggestsonicfan** [comment]
You are free to fork the project and redesign with and ESP-12.

**Comment by mackieks** [comment]
Shinobi 2, using a commodity ESP8285 and more efficient voltage regulators, has been tested and released.
